import { MeshSession, AgentMessage, ToolDefinition } from './meshTypes';
import { registry } from './registry';
import { opoRuntime } from './opoRuntime';
import { ResourceBroker } from '../engine/broker/resource-broker';
import { GuardrailMiddleware } from '../engine/guardrails/middleware';
import { HILManager } from '../engine/hil/hil-manager';
import { callLLM, LLMProvider } from './llm';
import { sanitizeMeshToolResult } from './queryResultGuard';
import {
  buildOpoQueryFromTemplate,
  formatRecurringQueriesForLLM,
  getRecurringQueriesForContext,
  PROTHEUS_RECURRING_QUERIES,
  GENERIC_RECURRING_QUERIES,
} from '@/lib/studio/recurringQueries';
import { matchRecurringQueryFromText } from '@/lib/studio/matchRecurringQuery';
import { runOpoQueryById, type ErpExecutionContext } from '@/lib/studio/runOpoQuery';
import { serializeOpoResponse } from '@/lib/studio/opoResponseParser';
import { getSessionMessages, appendMessage, setAgentContext } from './sessionMemory';
import { buildConsultaSummary } from '@/lib/studio/consultasSummary';

export class AgentExecutor {
  
  /**
   * Generates a stream of AgentMessages by executing the pipeline.
   */
  async *executePipeline(
    session: MeshSession,
    apiKeys: Record<string, string> = {},
    llmConfig?: {
      currentProvider?: string;
      llmConfigs?: Record<string, { apiKey?: string; baseUrl?: string; model?: string }>;
    },
    erpExecution: ErpExecutionContext = { mode: 'mock' }
  ): AsyncGenerator<AgentMessage> {
    const { intent, ontologySnapshot, messages } = session;
    const projectName = ontologySnapshot?.projectName ?? (ontologySnapshot as any)?.name ?? null;

    opoRuntime.setContext({
      erpExecution,
      ontology: ontologySnapshot,
      projectName,
    });

    yield {
      id: `msg-${Date.now()}-plan`,
      role: 'system',
      content: `OPO Swarm initialized. Semantic routing determined pipeline: [${intent.agentPipeline.join(' -> ')}]`,
      timestamp: new Date().toISOString()
    };

    const storedMessages = await getSessionMessages(session.id);
    const pipelineHistory = storedMessages && storedMessages.length > 0 ? storedMessages : [...messages];

    for (const agentId of intent.agentPipeline) {
      const agent = registry.getAgent(agentId);
      if (!agent) {
        yield {
          id: `msg-${Date.now()}-err`,
          agentId,
          role: 'system',
          content: `Agent ${agentId} not found in registry. Skipping.`,
          timestamp: new Date().toISOString()
        };
        continue;
      }

      // Check if this agent requires human approval (simulated logic based on name or metadata)
      // In a real flow, this would be based on the node connections
      if (agent.name.toLowerCase().includes('approval') || agent.systemPrompt.includes('APPROVAL_REQUIRED')) {
         // GROK OPTIMIZATION: Capture the *real* requestId generated by HILManager so the Studio console can drive approvals
         yield {
           id: `msg-${Date.now()}-hil`,
           agentId,
           role: 'system',
           content: `⏳ El agente ${agent.name} está esperando confirmación...`,
           timestamp: new Date().toISOString()
         };

         const hilResult = await HILManager.requestApproval(agentId, { pipelineHistory });
         const requestIdForUi = hilResult.requestId;

         // Re-yield a machine readable HIL event the console can key off for nice Approve/Reject UI
         yield {
           id: `msg-${Date.now()}-hilreq`,
           agentId,
           role: 'system',
           content: `⏳ HIL pendiente — requestId=${requestIdForUi}`,
           timestamp: new Date().toISOString(),
           hilRequestId: requestIdForUi
         } as any;

         if (!hilResult.approved) {
           yield {
             id: `msg-${Date.now()}-rej`,
             agentId,
             role: 'system',
             content: `❌ Acción cancelada por el usuario. Deteniendo ejecución.`,
             timestamp: new Date().toISOString()
           };
           return;
         }
         
         yield {
           id: `msg-${Date.now()}-apprv`,
           agentId,
           role: 'system',
           content: `✅ Acción confirmada. Reanudando ejecución.`,
           timestamp: new Date().toISOString()
         };
      }

      yield {
        id: `msg-${Date.now()}-start-${agentId}`,
        agentId,
        role: 'system',
        content: `Handing over to ${agent.name}...`,
        timestamp: new Date().toISOString()
      };

      if (agentId === 'data-querier') {
        const matched = matchRecurringQueryFromText(
          intent.rawQuery,
          ontologySnapshot,
          projectName
        );

        if (matched) {
          yield {
            id: `msg-${Date.now()}-opo-match`,
            agentId,
            role: 'system',
            content: `📊 Consulta recurrente detectada: ${matched.query.humanLabel} (${erpExecution.mode === 'live' ? 'datos en vivo' : 'demostración'})`,
            timestamp: new Date().toISOString(),
          };

          try {
            const result = await runOpoQueryById(
              matched.query.id,
              matched.paramValues,
              ontologySnapshot,
              projectName,
              erpExecution
            );
            const sourceQuery = buildOpoQueryFromTemplate(matched.query, matched.paramValues);
            const serialized = serializeOpoResponse({
              data: result.data,
              pagination: result.pagination,
              sourceQuery,
            });
            const summary = buildConsultaSummary(matched.query, result.data, result.pagination);
            const content = `${summary}\n\n${serialized}`;

            const queryResponse: AgentMessage = {
              id: `msg-${Date.now()}-${agentId}-opo`,
              agentId,
              role: 'assistant',
              content,
              timestamp: new Date().toISOString(),
            };
            yield queryResponse;
            pipelineHistory.push(queryResponse);
            await appendMessage(session.id, queryResponse);
            continue;
          } catch (queryErr: unknown) {
            const message = queryErr instanceof Error ? queryErr.message : 'OPO query failed';
            yield {
              id: `msg-${Date.now()}-opo-err`,
              agentId,
              role: 'system',
              content: `⚠️ Consulta OPO falló: ${message}. Continuando con razonamiento LLM.`,
              timestamp: new Date().toISOString(),
            };
          }
        }
      }

      const tools = registry.getToolsForAgent(agentId);
      
      const functionDeclarations = tools.flatMap(tool => 
        tool.operations.map(op => ({
          name: op.name,
          description: op.description || `Execute ${op.name} on ${tool.name}`,
          parameters: {
            type: 'object' as const,
            properties: op.inputSchema || {},
          }
        }))
      );

      const contents = pipelineHistory.map(msg => ({
        role: msg.role === 'assistant' ? 'model' as const : 'user' as const,
        parts: [{ text: msg.content }]
      }));

      if (contents.length === 0) {
        contents.push({ role: 'user' as const, parts: [{ text: intent.rawQuery }] });
      }

      // GROK FIX (prev critical + tsc): declare in scope so release and escalation catch can reference without ReferenceError
      let vaultKeyId: string | undefined;
      let responseText = '';

      try {
        // 1. Determine provider: prefer per-agent from node data (canvas AgentNode llmProvider set in SidebarRight), else job/ request llmConfig, else first in apiKeys, else safe default
        const nodeDataProvider = (agent as any).llmProvider as LLMProvider | undefined; // from packaged/compiled agent node metadata
        const passedProvider = llmConfig?.currentProvider as LLMProvider | undefined;
        const cfgForProvider = llmConfig?.llmConfigs?.[passedProvider || nodeDataProvider || ''] || 
                               llmConfig?.llmConfigs?.[Object.keys(llmConfig?.llmConfigs || {})[0] || ''];
        const provider: LLMProvider = nodeDataProvider || passedProvider || 
          (apiKeys && Object.keys(apiKeys)[0] as LLMProvider) || 'gemini';

        // Resolve key + model + base from passed apiKeys (primary for headless/studio triggers) + llmConfig (full per-prov)
        let apiKey = apiKeys[provider] || apiKeys.gemini || apiKeys.openai || '';
        let model = (agent as any).llmModel || cfgForProvider?.model;
        let baseUrl: string | undefined = cfgForProvider?.baseUrl;

        // Also check llmConfig for the chosen provider explicitly
        const explicitCfg = llmConfig?.llmConfigs?.[provider];
        if (explicitCfg) {
          if (explicitCfg.apiKey) apiKey = explicitCfg.apiKey;
          if (explicitCfg.model && !model) model = explicitCfg.model;
          if (explicitCfg.baseUrl) baseUrl = explicitCfg.baseUrl;
        }
        // Final fallback to plain apiKeys map for the provider
        if (!apiKey && apiKeys[provider]) apiKey = apiKeys[provider];

        if (!apiKey && provider !== 'ollama' && provider !== 'open-code') {
          throw new Error(`Missing API key for provider "${provider}". Configure in Settings (or per-agent) before running mesh/swarm.`);
        }

        // GROK 3A risk mitigation: build sanitized view of the ontology right after we know if this call is local vs cloud.
        // Cloud LLMs never receive raw physical table names or exact row counts from the user's DB.
        const isLocalProvider = provider === 'ollama' || provider === 'open-code';
        const sanitizedEntities = (ontologySnapshot.entities || []).map((e: any) => {
          const base: any = {
            name: e.name,
            description: e.description,
            attributes: (e.attributes || []).map((a: any) => ({ name: a.name, type: a.type, isPrimaryKey: !!a.isPrimaryKey, comment: a.comment, length: a.length }))
          };
          if (isLocalProvider) {
            base.originalTable = e.originalTable;
            base.rowCount = e.rowCount;
          } else {
            const rc = e.rowCount || 0;
            base.volume = rc > 100000 ? 'very_high' : rc > 10000 ? 'high' : rc > 1000 ? 'medium' : 'low';
          }
          return base;
        });

        const recurringBlock =
          agentId === 'data-querier' || agentId === 'data-analyst'
            ? formatRecurringQueriesForLLM(
                getRecurringQueriesForContext(ontologySnapshot, projectName || '')
              )
            : '';

        const systemInstruction = `
${agent.systemPrompt}

You have access to the following business ontology:
${JSON.stringify({ entities: sanitizedEntities }, null, 2)}

Data volume note: ${isLocalProvider ? 'Exact rowCount included for prioritization of core (high-volume) structures.' : 'Only volume buckets (very_high/high/medium/low) — no exact counts or physical names sent to third-party models.'}

${recurringBlock ? `${recurringBlock}\nWhen answering business questions, prefer executing the matching OPO-QL template via execute_query. Return results as JSON with data[] and pagination (hasNextPage, endCursor).` : ''}
`;

        // 2. Wrap LLM call with Guardrails + multi-provider support, respecting per-agent if set
        const isStrictSchema = agent.systemPrompt.includes('STRICT_JSON');
        
        let responseText = '';
        let toolCallPart: any = null;

        const llmCaller = async (retryContext?: string) => {
           if (retryContext) {
             contents.push({ role: 'user' as const, parts: [{ text: retryContext }] });
           }

           const fullPrompt = contents.map(c => c.parts[0].text).join('\n');

           const callOpts: any = {
             provider,
             apiKey: (provider === 'ollama' || provider === 'open-code') && baseUrl ? baseUrl : apiKey,
             systemInstruction,
           };
           if (model) callOpts.model = model;
           if (baseUrl && (provider === 'ollama' || provider === 'open-code')) callOpts.apiKey = baseUrl; // ensure baseUrl for local

           const text = await callLLM(fullPrompt, callOpts);

           // Very basic toolCall detection for now (can be improved per provider)
           if (text.includes('TOOL:')) {
             const match = text.match(/TOOL:\s*(\w+)\s*(\{.*\})/s);
             if (match) {
               try {
                 toolCallPart = {
                   functionCall: {
                     name: match[1],
                     args: JSON.parse(match[2])
                   }
                 };
               } catch (e) {}
             }
           } else if (text.includes('functionCall')) {
             try {
               const parsed = JSON.parse(text);
               if (parsed.functionCall) {
                 toolCallPart = parsed;
               }
             } catch (e) {
               const jsonMatch = text.match(/(\{[\s\S]*\})/);
               if (jsonMatch) {
                 try {
                   const parsed = JSON.parse(jsonMatch[1]);
                   if (parsed.functionCall) {
                     toolCallPart = parsed;
                   }
                 } catch (err) {}
               }
             }
           }

           if (isStrictSchema && !toolCallPart) {
             return text || '{}';
           }
           return text || 'No response generated.';
        };

        if (isStrictSchema) {
           const dummySchema = { type: 'object' };
           const validatedObj = await GuardrailMiddleware.executeWithGuardrails({
             schema: dummySchema,
             llmCaller,
             maxRetries: 3
           });
           responseText = JSON.stringify(validatedObj, null, 2);
        } else {
           responseText = await llmCaller();
        }

        // 3. Release key after execution
        if (vaultKeyId) {
           // Rough token estimation based on characters
           const estimatedTokens = Math.floor(JSON.stringify(contents).length / 4);
           await ResourceBroker.releaseKey(vaultKeyId, estimatedTokens);
        }

        if (toolCallPart?.functionCall) {
          const fc = toolCallPart.functionCall;
          
          yield {
            id: `msg-${Date.now()}-toolcall-${agentId}`,
            agentId,
            role: 'system',
            content: `🔧 Tool call: ${fc.name}(${JSON.stringify(fc.args || {})})`,
            timestamp: new Date().toISOString()
          };

          const matchedTool = tools.find(t => 
            t.operations.some(op => op.name === fc.name)
          );

          if (matchedTool) {
            const toolResult = await opoRuntime.executeTool(matchedTool, fc.name || '', fc.args || {});
            if (agentId === 'data-querier' && fc.name === 'execute_query') {
              const queryResult = toolResult as { status: string; data?: any };
              if (queryResult.status === 'success' && queryResult.data) {
                const runResult = queryResult.data;
                const template = fc.args.queryId
                  ? getRecurringQueriesForContext(ontologySnapshot, projectName).find(q => q.id === fc.args.queryId) ||
                    PROTHEUS_RECURRING_QUERIES.find(q => q.id === fc.args.queryId) ||
                    GENERIC_RECURRING_QUERIES.find(q => q.id === fc.args.queryId)
                  : null;
                const sourceQuery = template
                  ? buildOpoQueryFromTemplate(template, fc.args.params as any)
                  : fc.args.query;
                const serialized = serializeOpoResponse({
                  data: runResult.data,
                  pagination: runResult.pagination,
                  sourceQuery: sourceQuery as any,
                });
                let summary = '';
                if (template) {
                  summary = buildConsultaSummary(template, runResult.data, runResult.pagination);
                }
                responseText = summary ? `${summary}\n\n${serialized}` : serialized;
              } else {
                const sanitized = sanitizeMeshToolResult(toolResult);
                responseText = `Tool ${fc.name} returned: ${sanitized}`;
              }
            } else {
              const sanitized = sanitizeMeshToolResult(toolResult);
              responseText = `Tool ${fc.name} returned: ${sanitized}`;
            }
          } else {
            responseText = `Tool ${fc.name} not found in registry.`;
          }
        }

        const agentResponse: AgentMessage = {
          id: `msg-${Date.now()}-${agentId}`,
          agentId,
          role: 'assistant',
          content: responseText,
          timestamp: new Date().toISOString()
        };

        yield agentResponse;
        pipelineHistory.push(agentResponse);
        await appendMessage(session.id, agentResponse);

        // Save agent context in Blackboard
        await setAgentContext(session.id, agentId, {
          lastResponse: responseText,
          timestamp: new Date().toISOString()
        });

      } catch (error: any) {
        const errorMsg = `⚠️ Agent ${agent.name} failed: ${error.message}`;

        // === Smart escalation to human superior (new in this build) ===
        if (error.message.includes("don't know") || 
            error.message.includes("uncertain") || 
            error.message.toLowerCase().includes("i cannot") ||
            error.message.includes("max retries")) {
          
          yield {
            id: `msg-${Date.now()}-escalate-${agentId}`,
            agentId,
            role: 'system',
            content: `🚨 El agente no está seguro o se trabó. Solicitando ayuda al usuario.`,
            timestamp: new Date().toISOString(),
            hilRequestId: `escalate-${Date.now()}`
          } as any;

          // Trigger proper HIL with clear "superior humano" context
          try {
            const approved = await HILManager.requestApproval(agentId, {
              reason: 'Agent uncertainty - requires human supervisor decision',
              originalError: error.message,
              lastResponse: responseText
            });
            if (!approved) {
              yield { id: `msg-${Date.now()}-rej`, agentId, role: 'system', content: `❌ Solicitud cancelada por el usuario. Deteniendo ejecución.`, timestamp: new Date().toISOString() };
              return;
            }
            yield { id: `msg-${Date.now()}-apprv`, agentId, role: 'system', content: `✅ Continuación confirmada por el usuario.`, timestamp: new Date().toISOString() };
          } catch (hilErr) {
            // fall through
          }
        }

        yield {
          id: `msg-${Date.now()}-err-${agentId}`,
          agentId,
          role: 'system',
          content: errorMsg,
          timestamp: new Date().toISOString()
        };
      }
    }

    opoRuntime.clearContext();

    yield {
      id: `msg-${Date.now()}-done`,
      role: 'system',
      content: 'Pipeline execution completed.',
      timestamp: new Date().toISOString()
    };
  }
}

export const agentExecutor = new AgentExecutor();
