import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { Node, Edge } from '@xyflow/react';
import { EntityNodeData, RelationEdgeData, EntityAttribute } from './studioTypes';

// Helper functions for code generation
const sanitizeName = (name: string) => name.replace(/[^a-zA-Z0-9]/g, '');
const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
const toPascalCase = (s: string) => capitalize(sanitizeName(s));
const toCamelCase = (s: string) => {
  const sanitized = sanitizeName(s);
  return sanitized.charAt(0).toLowerCase() + sanitized.slice(1);
};

const PROTHEUS_TABLE_PATTERN = /^(SA|SB|SC|SF|SE|SX)\d/i;

function isProtheusErpProject(projectName: string, entityNodes: Node<EntityNodeData>[]): boolean {
  const name = projectName.toLowerCase();
  if (name.includes('protheus') || name.includes('totvs')) return true;
  return entityNodes.some((n) => PROTHEUS_TABLE_PATTERN.test(n.data.label?.trim() ?? ''));
}

export const generateAndDownloadMCP = async (nodes: Node<EntityNodeData>[], edges: Edge<RelationEdgeData>[], projectName: string) => {
  const zip = new JSZip();

  const safeName = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const folderName = `mcp-${safeName}`;
  const root = zip.folder(folderName)!;

  const entityNodes = nodes.filter(n => n.type === 'entityNode');
  const isProtheusErp = isProtheusErpProject(projectName, entityNodes);
  const allowSqlMutations = !isProtheusErp;
  
  // Package.json
  const packageJson = {
    name: folderName,
    version: '1.0.0',
    description: `MCP Server generated by OPO Studio for ${projectName}`,
    main: 'build/index.js',
    scripts: {
      "postinstall": "prisma generate",
      "db:push": "prisma db push",
      "build": "prisma generate && tsc",
      "start": "node build/index.js",
      "start:sse": "node build/sse.js",
      "setup": "prisma generate && prisma db push && tsc"
    },
    dependencies: {
      "@modelcontextprotocol/sdk": "^1.5.0",
      "@prisma/client": "^6.0.0",
      "express": "^4.21.0"
    },
    devDependencies: {
      "prisma": "^6.0.0",
      "typescript": "^5.0.0",
      "@types/node": "^20.0.0"
    }
  };
  root.file('package.json', JSON.stringify(packageJson, null, 2));

  // Tsconfig.json
  const tsconfig = {
    compilerOptions: {
      target: 'ES2022',
      module: 'CommonJS',
      moduleResolution: 'node',
      outDir: './build',
      rootDir: './src',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true
    },
    include: ['src/**/*']
  };
  root.file('tsconfig.json', JSON.stringify(tsconfig, null, 2));

  // README.md
  const readme = `# ${projectName} - MCP Server
Generated by OPO Studio.
${isProtheusErp ? '\n> **Protheus ERP detected:** mutations are read-only by default. Use REST/TLPP endpoints for CREATE/UPDATE/DELETE.\n' : ''}
## Quick Start
\`\`\`bash
npm install
npm run setup
npm start
\`\`\`

## Integración con Claude Desktop
Añade esto a tu \`claude_desktop_config.json\`:
\`\`\`json
{
  "mcpServers": {
    "${safeName}": {
      "command": "node",
      "args": ["/ruta/absoluta/a/este/proyecto/build/index.js"]
    }
  }
}
\`\`\`

## Testing Local con MCP Inspector
\`\`\`bash
npx @modelcontextprotocol/inspector node build/index.js
\`\`\`

## OPO Cognitive Mesh Integration
Para usar este servidor como herramienta (ToolNode) en OPO Cognitive Mesh, debes iniciarlo en modo SSE:
\`\`\`bash
npm run start:sse
\`\`\`
Luego, en OPO Studio, configura el Endpoint del ToolNode como \`http://localhost:3001/sse\`.
`;
  root.file('README.md', readme);

  if (isProtheusErp) {
    root.file(
      '.well-known/opo.json',
      JSON.stringify(
        {
          opo_version: '0.1.0',
          system_identity: { erp_name: 'TOTVS Protheus', organization_name: projectName },
          adapter_configuration: {
            readOnly: true,
            mutationStrategy: 'rest',
            protocol_interface: 'REST',
          },
        },
        null,
        2
      )
    );
  }

  // .env
  root.file('.env', `DATABASE_URL="file:./dev.db"`);

  // Prisma Schema Generation
  let prismaSchema = `// Generado por OPO Studio\ngenerator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "sqlite"\n  url      = env("DATABASE_URL")\n}\n\n`;
  
  // Mapping of outgoing relations for each node
  const outgoingRelations = new Map<string, Array<{ edge: Edge<RelationEdgeData>, targetNode: Node<EntityNodeData> }>>();
  const incomingRelations = new Map<string, Array<{ edge: Edge<RelationEdgeData>, sourceNode: Node<EntityNodeData> }>>();

  edges.forEach(edge => {
    const sourceNode = entityNodes.find(n => n.id === edge.source);
    const targetNode = entityNodes.find(n => n.id === edge.target);
    if (sourceNode && targetNode) {
      if (!outgoingRelations.has(sourceNode.id)) outgoingRelations.set(sourceNode.id, []);
      outgoingRelations.get(sourceNode.id)!.push({ edge, targetNode });
      
      if (!incomingRelations.has(targetNode.id)) incomingRelations.set(targetNode.id, []);
      incomingRelations.get(targetNode.id)!.push({ edge, sourceNode });
    }
  });

  entityNodes.forEach(node => {
    const modelName = toPascalCase(node.data.label);
    prismaSchema += `model ${modelName} {\n`;
    
    let hasPk = false;
    const attributes = (node.data.attributes as EntityAttribute[]) || [];
    
    attributes.forEach(attr => {
      let fieldLine = `  ${toCamelCase(attr.name)} ${attr.type === 'DateTime' ? 'DateTime' : attr.type}`;
      if (!attr.isRequired && !attr.isPrimaryKey) fieldLine += '?';
      if (attr.isPrimaryKey) {
        fieldLine += ` @id`;
        if (attr.type === 'String') fieldLine += ` @default(cuid())`;
        if (attr.type === 'Int') fieldLine += ` @default(autoincrement())`;
        hasPk = true;
      }
      if (attr.isUnique) fieldLine += ` @unique`;
      prismaSchema += fieldLine + '\n';
    });

    if (!hasPk) {
      prismaSchema += `  id String @id @default(cuid())\n`;
    }

    // Process relations (Target side - this model is Source)
    const outRels = outgoingRelations.get(node.id) || [];
    outRels.forEach(rel => {
      const targetModel = toPascalCase(rel.targetNode.data.label);
      const sourceField = rel.edge.data?.sourceFieldName || `${toCamelCase(targetModel)}s`;
      const card = rel.edge.data?.cardinality || 'ONE_TO_MANY';
      
      if (card === 'ONE_TO_MANY' || card === 'MANY_TO_MANY') {
        prismaSchema += `  ${sourceField} ${targetModel}[]\n`;
      } else if (card === 'ONE_TO_ONE') {
        prismaSchema += `  ${sourceField} ${targetModel}?\n`;
      }
    });

    // Process relations (Source side - this model is Target)
    const incRels = incomingRelations.get(node.id) || [];
    incRels.forEach(rel => {
      const sourceModel = toPascalCase(rel.sourceNode.data.label);
      const targetField = rel.edge.data?.targetFieldName || toCamelCase(sourceModel);
      const card = rel.edge.data?.cardinality || 'ONE_TO_MANY';
      
      if (card === 'ONE_TO_MANY' || card === 'ONE_TO_ONE') {
        prismaSchema += `  ${targetField} ${sourceModel}? @relation(fields: [${targetField}Id], references: [${hasPk ? toCamelCase(attributes.find(a => a.isPrimaryKey)!.name) : 'id'}])\n`;
        prismaSchema += `  ${targetField}Id String?${card === 'ONE_TO_ONE' ? ' @unique' : ''}\n`;
      } else if (card === 'MANY_TO_MANY') {
        prismaSchema += `  ${targetField}s ${sourceModel}[]\n`;
      }
    });

    prismaSchema += `}\n\n`;
  });

  const prismaFolder = root.folder('prisma')!;
  prismaFolder.file('schema.prisma', prismaSchema);

  // Src logic
  const srcFolder = root.folder('src')!;
  
  // prisma.ts
  srcFolder.file('prisma.ts', `import { PrismaClient } from '@prisma/client';\n\nexport const prisma = new PrismaClient();\n`);

  // Tools Generation
  const toolsFolder = srcFolder.folder('tools')!;
  let toolsTs = `import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { prisma } from "./prisma.js";\n\n`;

  const generatedTools: string[] = [];
  const generatedHandlers: string[] = [];

  entityNodes.forEach(node => {
    const modelName = toPascalCase(node.data.label);
    const varName = toCamelCase(modelName);
    const attributes = (node.data.attributes as EntityAttribute[]) || [];
    
    let pkName = 'id';
    let pkType = 'String';
    const pkAttr = attributes.find(a => a.isPrimaryKey);
    if (pkAttr) {
      pkName = toCamelCase(pkAttr.name);
      pkType = pkAttr.type;
    }

    const mcpSafeName = varName.toLowerCase();
    
    // Tools declarations
    if (allowSqlMutations) {
      generatedTools.push(`
    {
      name: "create_${mcpSafeName}",
      description: "Create a new ${modelName}",
      inputSchema: {
        type: "object",
        properties: {
          data: { type: "object" }
        },
        required: ["data"]
      }
    }`);
    }

    generatedTools.push(`
    {
      name: "get_${mcpSafeName}",
      description: "Get ${modelName} by ID",
      inputSchema: {
        type: "object",
        properties: {
          id: { type: "string" }
        },
        required: ["id"]
      }
    },
    {
      name: "search_${mcpSafeName}",
      description: "List ${modelName}s",
      inputSchema: {
        type: "object",
        properties: {
          take: { type: "number" },
          skip: { type: "number" }
        }
      }
    }${allowSqlMutations ? `,
    {
      name: "update_${mcpSafeName}",
      description: "Update ${modelName}",
      inputSchema: {
        type: "object",
        properties: {
          id: { type: "string" },
          data: { type: "object" }
        },
        required: ["id", "data"]
      }
    },
    {
      name: "delete_${mcpSafeName}",
      description: "Delete ${modelName}",
      inputSchema: {
        type: "object",
        properties: {
          id: { type: "string" }
        },
        required: ["id"]
      }
    }` : ''}`);

    // Handlers
    if (allowSqlMutations) {
      generatedHandlers.push(`
      if (request.params.name === "create_${mcpSafeName}") {
        const result = await prisma.${varName}.create({ data: args.data as any });
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
      }`);
    }

    generatedHandlers.push(`
      if (request.params.name === "get_${mcpSafeName}") {
        const idVal = ${pkType === 'Int' ? 'parseInt(args.id as string, 10)' : 'args.id as string'};
        const result = await prisma.${varName}.findUnique({ where: { ${pkName}: idVal } });
        if (!result) throw new Error("${modelName} not found");
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
      }
      if (request.params.name === "search_${mcpSafeName}") {
        const take = args.take ? Number(args.take) : 10;
        const skip = args.skip ? Number(args.skip) : 0;
        const result = await prisma.${varName}.findMany({ take, skip });
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
      }${allowSqlMutations ? `
      if (request.params.name === "update_${mcpSafeName}") {
        const idVal = ${pkType === 'Int' ? 'parseInt(args.id as string, 10)' : 'args.id as string'};
        const result = await prisma.${varName}.update({
          where: { ${pkName}: idVal },
          data: args.data as any
        });
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
      }
      if (request.params.name === "delete_${mcpSafeName}") {
        const idVal = ${pkType === 'Int' ? 'parseInt(args.id as string, 10)' : 'args.id as string'};
        const result = await prisma.${varName}.delete({ where: { ${pkName}: idVal } });
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
      }` : ''}`);
      
    // Relational Handlers (Outgoing)
    const outRels = outgoingRelations.get(node.id) || [];
    outRels.forEach(rel => {
      const targetModel = toPascalCase(rel.targetNode.data.label);
      const sourceField = rel.edge.data?.sourceFieldName || `${toCamelCase(targetModel)}s`;
      const relationToolName = `get_${mcpSafeName}_${sourceField}`;
      
      generatedTools.push(`
    {
      name: "${relationToolName}",
      description: "Get ${sourceField} for a given ${modelName}",
      inputSchema: {
        type: "object",
        properties: {
          id: { type: "string" }
        },
        required: ["id"]
      }
    }`);

      generatedHandlers.push(`
      if (request.params.name === "${relationToolName}") {
        const idVal = ${pkType === 'Int' ? 'parseInt(args.id as string, 10)' : 'args.id as string'};
        const result = await prisma.${varName}.findUnique({
          where: { ${pkName}: idVal },
          include: { ${sourceField}: true }
        });
        if (!result) throw new Error("${modelName} not found");
        return { content: [{ type: "text", text: JSON.stringify((result as any)[Object.keys({${sourceField}:1})[0]], null, 2) }] };
      }`);
    });
  });

  toolsTs += `
export const server = new Server(
  { name: "${safeName}-mcp", version: "1.0.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return { tools: [${generatedTools.join(',')}] };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  try {
    const args = request.params.arguments || {};
${generatedHandlers.join('')}
    throw new Error("Tool not found: " + request.params.name);
  } catch (error: any) {
    return {
      content: [{ type: "text", text: \`Error: \${error.message}\` }],
      isError: true,
    };
  }
});
`;
  srcFolder.file('tools.ts', toolsTs);

  let indexTs = `import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { server } from "./tools.js";

async function run() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("${projectName} MCP Server running on stdio");
}

run().catch((error) => {
  console.error("Fatal error running server:", error);
  process.exit(1);
});
`;

  srcFolder.file('index.ts', indexTs);

  const sseTs = `import express from "express";
import { SSEServerTransport } from "@modelcontextprotocol/sdk/server/sse.js";
import { server } from "./tools.js";

const app = express();
const PORT = process.env.PORT || 3001;

let transport: SSEServerTransport | null = null;

app.get("/sse", async (req, res) => {
  console.log("New SSE connection established");
  transport = new SSEServerTransport("/messages", res);
  await server.connect(transport);
});

app.post("/messages", async (req, res) => {
  if (!transport) {
    res.status(400).send("SSE transport not initialized");
    return;
  }
  await transport.handlePostMessage(req, res);
});

app.listen(PORT, () => {
  console.log(\`${projectName} MCP Server running on SSE at http://localhost:\${PORT}/sse\`);
});
`;
  srcFolder.file('sse.ts', sseTs);

  const content = await zip.generateAsync({ type: 'blob' });
  saveAs(content, `${folderName}.zip`);
};

