/**
 * Claver AutoPool — pool vivo de automatizaciones instantáneas
 *
 * Lema del pool: «Prendelo una vez. Labura todos los días.»
 * Sublema: «Sin técnico. Sin espera. Sin excusas.»
 *
 * Cada entrada es un SKU auto-provisionable con lema propio + nicho detectable.
 * Nuevos servicios se suman vía vibe coding: copiar AUTOPOOL_ENTRY_TEMPLATE al final.
 */

export const AUTOPOOL_BRAND = {
  id: "claver-autopool",
  name: "AutoPool",
  fullName: "Claver AutoPool",
  lema: "Prendelo una vez. Labura todos los días.",
  sublema: "Sin técnico. Sin espera. Sin excusas.",
  descriptor:
    "Automatizaciones que se activan solas en minutos. Un pool que crece todos los días.",
  badge: "⚡ AutoPool",
  href: "/claver/apps?pool=autopool",
} as const

/** Nichos de automatización — filtro UI, ads y command palette */
export const AUTOPOOL_NICHOS = {
  protege: {
    id: "protege",
    label: "Protege",
    lema: "Que nada te robe el sueño.",
    emoji: "🛡️",
    color: "violet",
    descripcion: "Seguridad, backup, acceso, cifrado.",
  },
  avisa: {
    id: "avisa",
    label: "Avisa",
    lema: "Enterate antes que el cliente.",
    emoji: "🔔",
    color: "amber",
    descripcion: "Alertas, reportes, monitoreo, recordatorios.",
  },
  carga: {
    id: "carga",
    label: "Carga",
    lema: "La foto reemplaza al teclado.",
    emoji: "📸",
    color: "orange",
    descripcion: "OCR, importación, conciliación, menos carga manual.",
  },
  atiende: {
    id: "atiende",
    label: "Atiende",
    lema: "Tu negocio responde aunque estés cerrado.",
    emoji: "💬",
    color: "fuchsia",
    descripcion: "Chat, IA, helpdesk, primera línea.",
  },
  cobra: {
    id: "cobra",
    label: "Cobra",
    lema: "El link cobra. Vos seguís.",
    emoji: "💳",
    color: "emerald",
    descripcion: "Pagos, links, QR, cobranzas.",
  },
  ordena: {
    id: "ordena",
    label: "Ordena",
    lema: "El tiempo se agenda solo.",
    emoji: "📅",
    color: "sky",
    descripcion: "Turnos, agenda, recordatorios de citas.",
  },
  mide: {
    id: "mide",
    label: "Mide",
    lema: "Los números llegan solos.",
    emoji: "📊",
    color: "cyan",
    descripcion: "KPIs, NPS, BI, encuestas.",
  },
  conecta: {
    id: "conecta",
    label: "Conecta",
    lema: "Un cable menos en tu vida.",
    emoji: "🔗",
    color: "blue",
    descripcion: "Comunicaciones, integraciones, canales.",
  },
  publica: {
    id: "publica",
    label: "Publica",
    lema: "Tu vitrina siempre actualizada.",
    emoji: "📣",
    color: "rose",
    descripcion: "Catálogos, landings, marketing automático.",
  },
  integra: {
    id: "integra",
    label: "Integra",
    lema: "Tu tienda y tu ERP hablan el mismo idioma.",
    emoji: "🔌",
    color: "indigo",
    descripcion: "Shopify, Tienda Nube, Odoo, ML, WooCommerce — sync real.",
  },
  implementa: {
    id: "implementa",
    label: "Implementa",
    lema: "Desde tu casa. Sin visita. Sin esperar al técnico.",
    emoji: "🏠",
    color: "lime",
    descripcion: "Onboarding, migraciones y parametrización remota guiada.",
  },
  releva: {
    id: "releva",
    label: "Releva",
    lema: "Preguntá. Medí. Mejorá sin salir a la calle.",
    emoji: "📋",
    color: "teal",
    descripcion: "Encuestas, formularios y relevamientos automáticos.",
  },
  marketea: {
    id: "marketea",
    label: "Marketea",
    lema: "Tu marca trabaja mientras vos laburás.",
    emoji: "🎯",
    color: "pink",
    descripcion: "Campañas, pixels, SEO, redes y email marketing.",
  },
} as const

export type AutopoolNichoId = keyof typeof AUTOPOOL_NICHOS

/** Sección principal del marketplace — filtro de primer nivel */
export const AUTOPOOL_TIPOS = {
  automation: {
    id: "automation",
    label: "Automatizaciones",
    emoji: "⚡",
    lema: "Prendelo una vez. Labura todos los días.",
  },
  integracion: {
    id: "integracion",
    label: "Integraciones",
    emoji: "🔌",
    lema: "Conectá tu stack en minutos.",
  },
  implementacion: {
    id: "implementacion",
    label: "Implementación remota",
    emoji: "🏠",
    lema: "Todo desde tu casa, con guía paso a paso.",
  },
  relevamiento: {
    id: "relevamiento",
    label: "Relevamientos y encuestas",
    emoji: "📋",
    lema: "Datos frescos sin encuestador en la calle.",
  },
  marketing: {
    id: "marketing",
    label: "Marketing",
    emoji: "🎯",
    lema: "Difundí sin depender de una agencia.",
  },
  intangible: {
    id: "intangible",
    label: "Servicios intangibles",
    emoji: "💎",
    lema: "Ahorro, ingresos y paz mental — sin tocar una línea de código.",
  },
} as const

export type AutopoolTipoId = keyof typeof AUTOPOOL_TIPOS

export type AutopoolMaturity = "seed" | "growing" | "stable"

export type AutopoolCertLevel = "GLOBAL_AUTO" | "REGION_AUTO" | "SEMI_AUTO"

export interface AutopoolEntry {
  sku: string
  nombre: string
  /** Lema del servicio — una línea memorable (aparece en card del marketplace) */
  lema: string
  /** Sección del marketplace */
  tipo: AutopoolTipoId
  nicho: AutopoolNichoId
  /** Tags para búsqueda, SEO y detección en command palette */
  vibeTags: string[]
  autoCertLevel: AutopoolCertLevel
  /** Mapeo a lib/integrations/catalog.ts cuando aplica */
  integracionId?: string
  /** Servicio ejecutable 100% remoto (desde casa) */
  remotoDesdeCasa: boolean
  precioDesdeArs: number
  tipoCobro: "mensual" | "por_uso" | "one_shot"
  maturity: AutopoolMaturity
  poolSince: string
  poolVersion: string
  impactoUniversal: 1 | 2 | 3 | 4 | 5
  activacionMinutos: number
  descripcionCorta: string
  playbookId: string
  destacado?: boolean
}

/** Pool MVP — Tier 1 universal + los que más venden. Crece diario. */
export const AUTOPOOL_ENTRIES: AutopoolEntry[] = [
  {
    sku: "sec.backup",
    nombre: "Backup Cloud",
    lema: "Dormí tranquilo. Tu data ya está guardada.",
    tipo: "automation",
    nicho: "protege",
    remotoDesdeCasa: true,
    vibeTags: ["backup", "respaldo", "seguridad", "disaster-recovery", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 4900,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 5,
    descripcionCorta: "Snapshot nocturno de tu ERP. Restauración self-service.",
    playbookId: "playbook.sec.backup",
    destacado: true,
  },
  {
    sku: "sec.mfa",
    nombre: "Escudo 2FA",
    lema: "Tu clave sola ya no alcanza.",
    tipo: "automation",
    nicho: "protege",
    remotoDesdeCasa: true,
    vibeTags: ["2fa", "mfa", "seguridad", "acceso", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 790,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 2,
    descripcionCorta: "Doble factor obligatorio por rol. Activación al próximo login.",
    playbookId: "playbook.sec.mfa",
    destacado: true,
  },
  {
    sku: "data.reportes_prog",
    nombre: "Mañanero",
    lema: "El resumen te espera antes del café.",
    tipo: "automation",
    nicho: "avisa",
    remotoDesdeCasa: true,
    vibeTags: ["reportes", "email", "kpi", "cron", "morning", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 2490,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 3,
    descripcionCorta: "Ventas, caja y stock en tu mail cada mañana.",
    playbookId: "playbook.data.reportes_prog",
    destacado: true,
  },
  {
    sku: "data.helpdesk_ia",
    nombre: "Primera Línea IA",
    lema: "La pregunta repetida ya tiene respuesta.",
    tipo: "automation",
    nicho: "atiende",
    remotoDesdeCasa: true,
    vibeTags: ["soporte", "ia", "helpdesk", "faq", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 14900,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 2,
    descripcionCorta: "Tickets resueltos por IA con docs de tu ERP.",
    playbookId: "playbook.data.helpdesk_ia",
    destacado: true,
  },
  {
    sku: "fiscal.ocr",
    nombre: "FotoFactura",
    lema: "Sacá la foto. Nosotros cargamos.",
    tipo: "automation",
    nicho: "carga",
    remotoDesdeCasa: true,
    vibeTags: ["ocr", "factura", "compras", "gemini", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 9900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 1,
    descripcionCorta: "OCR de facturas de proveedor → borrador en compras.",
    playbookId: "playbook.fiscal.ocr",
    destacado: true,
  },
  {
    sku: "infra.uptime",
    nombre: "Vigía",
    lema: "Si se cae, te llega antes que al cliente.",
    tipo: "automation",
    nicho: "avisa",
    remotoDesdeCasa: true,
    vibeTags: ["uptime", "monitor", "alerta", "status", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 2490,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 5,
    descripcionCorta: "Monitoreo 24/7 de tu ERP y tienda.",
    playbookId: "playbook.infra.uptime",
  },
  {
    sku: "data.nps",
    nombre: "Pulso Cliente",
    lema: "Sabés si lo hiciste bien sin preguntar a mano.",
    tipo: "automation",
    nicho: "mide",
    remotoDesdeCasa: true,
    vibeTags: ["nps", "encuesta", "satisfaccion", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 3490,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 3,
    descripcionCorta: "Encuesta 1-10 automática post-venta.",
    playbookId: "playbook.data.nps",
  },
  {
    sku: "com.chat",
    nombre: "Mostrador Digital",
    lema: "Atendé en la web mientras laburás en el depósito.",
    tipo: "automation",
    nicho: "atiende",
    remotoDesdeCasa: true,
    vibeTags: ["chat", "widget", "ia", "web", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 3490,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 2,
    descripcionCorta: "Chat embebido con IA que conoce tu catálogo.",
    playbookId: "playbook.com.chat",
  },
  {
    sku: "fiscal.conciliacion",
    nombre: "Cierra Banco",
    lema: "El extracto y tu sistema por fin coinciden.",
    tipo: "automation",
    nicho: "carga",
    remotoDesdeCasa: true,
    vibeTags: ["banco", "conciliacion", "csv", "tesoreria", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 6900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 5,
    descripcionCorta: "Importá CSV y matcheá movimientos automático.",
    playbookId: "playbook.fiscal.conciliacion",
  },
  {
    sku: "com.whatsapp",
    nombre: "WhatsApp ON",
    lema: "El pedido confirmado llega al celular del cliente.",
    tipo: "automation",
    nicho: "conecta",
    remotoDesdeCasa: true,
    vibeTags: ["whatsapp", "twilio", "mensajes", "automatico"],
    autoCertLevel: "REGION_AUTO",
    precioDesdeArs: 7900,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 15,
    descripcionCorta: "Plantillas aprobadas + webhooks al ERP.",
    playbookId: "playbook.com.whatsapp",
    destacado: true,
  },
  {
    sku: "ops.agenda_web",
    nombre: "Turnero",
    lema: "Reservá online. Confirmá solo.",
    tipo: "automation",
    nicho: "ordena",
    remotoDesdeCasa: true,
    vibeTags: ["agenda", "turnos", "online", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 3900,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 3,
    descripcionCorta: "Agenda pública con confirmación automática.",
    playbookId: "playbook.ops.agenda_web",
  },
  {
    sku: "mkt.catalogo_pdf",
    nombre: "Catálogo Vivo",
    lema: "El PDF se actualiza cuando cambiás el precio.",
    tipo: "marketing",
    nicho: "publica",
    remotoDesdeCasa: true,
    vibeTags: ["pdf", "catalogo", "precios", "b2b", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 2900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 3,
    activacionMinutos: 5,
    descripcionCorta: "Link de descarga siempre al día.",
    playbookId: "playbook.mkt.catalogo_pdf",
  },

  // ── Integraciones e-commerce (sync real en repo) ───────────────────────────
  {
    sku: "integ.shopify",
    nombre: "Shopify Link",
    lema: "Tu Shopify y el depósito, un solo stock.",
    tipo: "integracion",
    nicho: "integra",
    integracionId: "shopify",
    remotoDesdeCasa: true,
    vibeTags: ["shopify", "ecommerce", "oauth", "stock", "pedidos", "sync"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 14900,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 10,
    descripcionCorta: "OAuth + sync productos, stock y pedidos. Webhooks incluidos.",
    playbookId: "playbook.integ.shopify",
    destacado: true,
  },
  {
    sku: "integ.tienda_nube",
    nombre: "Tienda Nube Link",
    lema: "El canal #1 argentino, sin Zapier.",
    tipo: "integracion",
    nicho: "integra",
    integracionId: "tienda_nube",
    remotoDesdeCasa: true,
    vibeTags: ["tienda-nube", "tiendanube", "ecommerce", "argentina", "oauth", "sync"],
    autoCertLevel: "REGION_AUTO",
    precioDesdeArs: 14900,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 10,
    descripcionCorta: "Conexión nativa OAuth. Pedidos bajan solos al ERP.",
    playbookId: "playbook.integ.tienda_nube",
    destacado: true,
  },
  {
    sku: "integ.odoo",
    nombre: "Odoo Bridge",
    lema: "Migrá de Odoo sin reescribir todo.",
    tipo: "integracion",
    nicho: "integra",
    integracionId: "odoo",
    remotoDesdeCasa: true,
    vibeTags: ["odoo", "migracion", "erp", "import", "sync", "xml-rpc"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 29900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 30,
    descripcionCorta: "Importá productos, contactos y saldos desde Odoo vía API.",
    playbookId: "playbook.integ.odoo",
    destacado: true,
  },
  {
    sku: "integ.mercado_libre",
    nombre: "Mercado Libre Link",
    lema: "Vendés en ML con el mismo stock del local.",
    tipo: "integracion",
    nicho: "integra",
    integracionId: "mercado_libre",
    remotoDesdeCasa: true,
    vibeTags: ["mercadolibre", "ml", "marketplace", "oauth", "sync"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 14900,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 15,
    descripcionCorta: "Publicaciones, ventas y stock sincronizados. Activación validada por analista.",
    playbookId: "playbook.integ.mercado_libre",
    destacado: true,
  },
  {
    sku: "integ.woocommerce",
    nombre: "WooCommerce Link",
    lema: "WordPress vende. Clavis manda.",
    tipo: "integracion",
    nicho: "integra",
    integracionId: "woocommerce",
    remotoDesdeCasa: true,
    vibeTags: ["woocommerce", "wordpress", "ecommerce", "api", "sync"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 12900,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 15,
    descripcionCorta: "REST API: catálogo, pedidos y stock bidireccional.",
    playbookId: "playbook.integ.woocommerce",
  },

  // ── Implementación remota (desde casa) ─────────────────────────────────────
  {
    sku: "impl.onboarding_ia",
    nombre: "Arranque Express",
    lema: "Rubro elegido. Sistema listo. Sin visita.",
    tipo: "implementacion",
    nicho: "implementa",
    remotoDesdeCasa: true,
    vibeTags: ["onboarding", "ia", "rubro", "parametrizacion", "remoto"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 0,
    tipoCobro: "one_shot",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 5,
    descripcionCorta: "Onboarding IA por rubro: módulos, maestros y demo en 5 min.",
    playbookId: "playbook.impl.onboarding_ia",
    destacado: true,
  },
  {
    sku: "impl.migracion_csv",
    nombre: "Importá Todo",
    lema: "Tu Excel entra. El sistema ordena.",
    tipo: "implementacion",
    nicho: "implementa",
    remotoDesdeCasa: true,
    vibeTags: ["migracion", "csv", "import", "productos", "clientes", "remoto"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 9900,
    tipoCobro: "one_shot",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 20,
    descripcionCorta: "Wizard CSV productos, clientes y proveedores con validación.",
    playbookId: "playbook.impl.migracion_csv",
  },
  {
    sku: "impl.migracion_odoo",
    nombre: "Salí de Odoo",
    lema: "Traé tus datos. Dejá el dolor.",
    tipo: "implementacion",
    nicho: "implementa",
    remotoDesdeCasa: true,
    vibeTags: ["odoo", "migracion", "erp", "remoto", "implementacion"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 49900,
    tipoCobro: "one_shot",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 60,
    descripcionCorta: "Migración guiada productos, contactos, saldos y histórico ventas.",
    playbookId: "playbook.impl.migracion_odoo",
    destacado: true,
  },
  {
    sku: "impl.migracion_shopify",
    nombre: "Traé tu Shopify",
    lema: "Catálogo y clientes, un solo clic de distancia.",
    tipo: "implementacion",
    nicho: "implementa",
    remotoDesdeCasa: true,
    vibeTags: ["shopify", "migracion", "import", "remoto"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 24900,
    tipoCobro: "one_shot",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 30,
    descripcionCorta: "Import inicial + activación sync continuo.",
    playbookId: "playbook.impl.migracion_shopify",
  },
  {
    sku: "impl.migracion_tienda_nube",
    nombre: "Traé tu Tienda Nube",
    lema: "Tu tienda ya vende. Ahora facturá bien.",
    tipo: "implementacion",
    nicho: "implementa",
    remotoDesdeCasa: true,
    vibeTags: ["tienda-nube", "migracion", "import", "remoto"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 24900,
    tipoCobro: "one_shot",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 30,
    descripcionCorta: "Import catálogo + pedidos históricos + OAuth sync.",
    playbookId: "playbook.impl.migracion_tienda_nube",
  },
  {
    sku: "impl.homologacion_afip",
    nombre: "AFIP Ready",
    lema: "Certificado cargado. Primera factura hoy.",
    tipo: "implementacion",
    nicho: "implementa",
    remotoDesdeCasa: true,
    vibeTags: ["afip", "certificado", "homologacion", "fiscal", "remoto"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 14900,
    tipoCobro: "one_shot",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 45,
    descripcionCorta: "Wizard remoto certificado + homologación + test CAE.",
    playbookId: "playbook.impl.homologacion_afip",
    destacado: true,
  },
  {
    sku: "impl.capacitacion_remota",
    nombre: "Academia en Casa",
    lema: "Tu equipo aprende sin que vaya nadie.",
    tipo: "implementacion",
    nicho: "implementa",
    remotoDesdeCasa: true,
    vibeTags: ["capacitacion", "video", "lms", "remoto", "equipo"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 7900,
    tipoCobro: "one_shot",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 5,
    descripcionCorta: "Microcursos por rubro y rol con certificado PDF.",
    playbookId: "playbook.impl.capacitacion_remota",
  },
  {
    sku: "impl.parametrizacion_remota",
    nombre: "Ajuste Fino",
    lema: "Listas, impuestos y series sin salir de tu silla.",
    tipo: "implementacion",
    nicho: "implementa",
    remotoDesdeCasa: true,
    vibeTags: ["parametrizacion", "listas-precio", "impuestos", "remoto"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 19900,
    tipoCobro: "one_shot",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 40,
    descripcionCorta: "Checklist guiado + IA para cerrar gaps de configuración.",
    playbookId: "playbook.impl.parametrizacion_remota",
  },

  // ── Relevamientos y encuestas ──────────────────────────────────────────────
  {
    sku: "releva.encuesta_clientes",
    nombre: "Voz del Cliente",
    lema: "Preguntá post-venta sin molestar.",
    tipo: "relevamiento",
    nicho: "releva",
    remotoDesdeCasa: true,
    vibeTags: ["encuesta", "clientes", "satisfaccion", "formulario", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 3490,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 5,
    descripcionCorta: "Encuestas automáticas por mail/WhatsApp tras cada venta.",
    playbookId: "playbook.releva.encuesta_clientes",
    destacado: true,
  },
  {
    sku: "releva.encuesta_empleados",
    nombre: "Pulso del Equipo",
    lema: "Clima laboral sin reuniones eternas.",
    tipo: "relevamiento",
    nicho: "releva",
    remotoDesdeCasa: true,
    vibeTags: ["encuesta", "empleados", "rrhh", "clima", "anonimo"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 4990,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 3,
    activacionMinutos: 5,
    descripcionCorta: "Encuestas anónimas programadas al equipo.",
    playbookId: "playbook.releva.encuesta_empleados",
  },
  {
    sku: "releva.formulario_web",
    nombre: "Formulario Pro",
    lema: "Cada consulta entra al CRM, no al mail.",
    tipo: "relevamiento",
    nicho: "releva",
    remotoDesdeCasa: true,
    vibeTags: ["formulario", "web", "leads", "crm", "embed"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 2900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 3,
    descripcionCorta: "Form embeddable → pipeline CRM automático.",
    playbookId: "playbook.releva.formulario_web",
  },
  {
    sku: "releva.relevamiento_mercado",
    nombre: "Radar de Mercado",
    lema: "Precios y competencia sin salir a relevar.",
    tipo: "relevamiento",
    nicho: "releva",
    remotoDesdeCasa: true,
    vibeTags: ["relevamiento", "mercado", "competencia", "precios", "ia"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 9900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 3,
    activacionMinutos: 15,
    descripcionCorta: "Plantillas de relevamiento + tablero comparativo.",
    playbookId: "playbook.releva.relevamiento_mercado",
  },
  {
    sku: "releva.post_compra",
    nombre: "Post-Compra",
    lema: "¿Cómo fue la experiencia? Lo sabés al toque.",
    tipo: "relevamiento",
    nicho: "releva",
    remotoDesdeCasa: true,
    vibeTags: ["post-compra", "csat", "encuesta", "ecommerce", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 2490,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 3,
    descripcionCorta: "CSAT automático en tienda, ML y Shopify.",
    playbookId: "playbook.releva.post_compra",
  },

  // ── Marketing ──────────────────────────────────────────────────────────────
  {
    sku: "mkt.pixel_ads",
    nombre: "Pixel Listo",
    lema: "Tus ads miden. Vos vendés.",
    tipo: "marketing",
    nicho: "marketea",
    remotoDesdeCasa: true,
    vibeTags: ["pixel", "meta", "google-ads", "remarketing", "automatico"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 1990,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 5,
    descripcionCorta: "Meta Pixel + GA4 en tu tienda en 3 clics.",
    playbookId: "playbook.mkt.pixel_ads",
    destacado: true,
  },
  {
    sku: "mkt.campanas_email",
    nombre: "Email Drip",
    lema: "La secuencia vende mientras dormís.",
    tipo: "marketing",
    nicho: "marketea",
    remotoDesdeCasa: true,
    vibeTags: ["email", "marketing", "drip", "automation", "resend"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 5900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 10,
    descripcionCorta: "Secuencias post-compra, abandono carrito y reactivación.",
    playbookId: "playbook.mkt.campanas_email",
  },
  {
    sku: "mkt.gbp_sync",
    nombre: "Maps ON",
    lema: "Google Maps con horarios y fotos al día.",
    tipo: "marketing",
    nicho: "marketea",
    remotoDesdeCasa: true,
    vibeTags: ["google", "maps", "gbp", "seo-local", "automatico"],
    autoCertLevel: "REGION_AUTO",
    precioDesdeArs: 4900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 15,
    descripcionCorta: "Sync horarios, fotos y ofertas desde el ERP.",
    playbookId: "playbook.mkt.gbp_sync",
  },
  {
    sku: "mkt.landing_rubro",
    nombre: "Landing Express",
    lema: "Tu rubro, tu página, hoy.",
    tipo: "marketing",
    nicho: "marketea",
    remotoDesdeCasa: true,
    vibeTags: ["landing", "rubro", "seo", "generacion-ia"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 4900,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 10,
    descripcionCorta: "Landing generada por onboarding IA + deploy CDN.",
    playbookId: "playbook.mkt.landing_rubro",
  },
  {
    sku: "mkt.redes_programadas",
    nombre: "Redes en Piloto",
    lema: "Publicá sin estar pegado al celular.",
    tipo: "marketing",
    nicho: "marketea",
    remotoDesdeCasa: true,
    vibeTags: ["redes", "instagram", "programacion", "contenido", "ia"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 7900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 3,
    activacionMinutos: 20,
    descripcionCorta: "Calendario de posts desde promociones y catálogo ERP.",
    playbookId: "playbook.mkt.redes_programadas",
  },
  {
    sku: "mkt.referidos",
    nombre: "Referí y Ganá",
    lema: "Tus clientes traen clientes.",
    tipo: "marketing",
    nicho: "marketea",
    remotoDesdeCasa: true,
    vibeTags: ["referidos", "viral", "wallet", "comision"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 0,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 5,
    descripcionCorta: "Código referido + crédito en cuenta automático.",
    playbookId: "playbook.mkt.referidos",
  },
  {
    sku: "pos.fiado_barrio",
    nombre: "Libreta Fiado",
    lema: "Fiá con límite. Que el otro se entere.",
    tipo: "intangible",
    nicho: "cobra",
    remotoDesdeCasa: true,
    vibeTags: ["fiado", "libreta", "almacen", "barrio", "kiosco", "credito", "email"],
    autoCertLevel: "GLOBAL_AUTO",
    precioDesdeArs: 4990,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 5,
    descripcionCorta: "Límite de crédito + email al fiador en cada compra fiado.",
    playbookId: "playbook.pos.fiado_barrio",
    destacado: true,
  },
  // ─── Servicios intangibles — Top 5 (bolsillo + ansiedad) ───
  {
    sku: "intang.cobranzas_wa",
    nombre: "Secretaria de Cobranzas WA",
    lema: "El link cobra. Vos seguís vendiendo.",
    tipo: "intangible",
    nicho: "cobra",
    remotoDesdeCasa: true,
    vibeTags: ["cobranzas", "whatsapp", "cxc", "mercadopago", "recupero", "pyme", "bolsillo"],
    autoCertLevel: "REGION_AUTO",
    precioDesdeArs: 20000,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 15,
    descripcionCorta:
      "Lee facturas vencidas del ERP y manda WhatsApp amable con link MercadoPago. Recupera caja día 1.",
    playbookId: "playbook.intang.cobranzas_wa",
    destacado: true,
  },
  {
    sku: "intang.reputation_firewall",
    nombre: "Escudo Reputación",
    lema: "Que una mala reseña no te cierre el negocio.",
    tipo: "intangible",
    nicho: "protege",
    remotoDesdeCasa: true,
    vibeTags: ["reputacion", "google", "tripadvisor", "crisis", "reseñas", "sms", "ansiedad"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 14900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 30,
    descripcionCorta:
      "Monitorea GBP, TripAdvisor y menciones. Alerta SMS en 1★ y sugiere respuesta conciliadora con IA.",
    playbookId: "playbook.intang.reputation_firewall",
    destacado: true,
  },
  {
    sku: "intang.legal_shield",
    nombre: "Legal Shield",
    lema: "Tu abogado de bolsillo en 30 segundos.",
    tipo: "intangible",
    nicho: "protege",
    remotoDesdeCasa: true,
    vibeTags: ["legal", "contratos", "pdf", "alquiler", "nda", "semáforo", "estafa"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 9900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 10,
    descripcionCorta:
      "Reenviá un PDF a legal@claver.com y recibí resumen semáforo: cláusulas abusivas vs OK.",
    playbookId: "playbook.intang.legal_shield",
    destacado: true,
  },
  {
    sku: "intang.subs_tax_scanner",
    nombre: "Cazador de Gastos Zombies",
    lema: "Recuperá plata que se te escapa sin que te des cuenta.",
    tipo: "intangible",
    nicho: "cobra",
    remotoDesdeCasa: true,
    vibeTags: ["b2c", "suscripciones", "impuestos", "ahorro", "tarjeta", "finanzas-personales"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 3000,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 20,
    descripcionCorta:
      "IA detecta suscripciones zombie e impuestos de más en resúmenes. Ahorro directo en el bolsillo.",
    playbookId: "playbook.intang.subs_tax_scanner",
  },
  {
    sku: "intang.reactivador_clientes",
    nombre: "Despertador de Clientes",
    lema: "Oro de la basura: clientes que no compran hace meses.",
    tipo: "intangible",
    nicho: "marketea",
    remotoDesdeCasa: true,
    vibeTags: ["reactivacion", "churn", "whatsapp", "sms", "growth", "roi", "dormidos"],
    autoCertLevel: "REGION_AUTO",
    precioDesdeArs: 12900,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-24",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 20,
    descripcionCorta:
      "Segmenta clientes inactivos 6+ meses y dispara WA/SMS personalizado con oferta. ROI en panel.",
    playbookId: "playbook.intang.reactivador_clientes",
    destacado: true,
  },
  // ─── Premium 7 — monetización clase SAP/Odoo (AR/LATAM) ───
  {
    sku: "intang.liquidacion_pagos",
    nombre: "Conciliador Liquidación MP y Tarjetas",
    lema: "Que no te roben ni un peso de comisión.",
    tipo: "intangible",
    nicho: "cobra",
    remotoDesdeCasa: true,
    vibeTags: ["mercadopago", "prisma", "modo", "conciliacion", "comisiones", "tesoreria"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 24900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-25",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 30,
    descripcionCorta:
      "Cruza ventas POS con liquidaciones MP/Prisma/MODO. Alerta WhatsApp si hay plata retenida o comisiones raras.",
    playbookId: "playbook.intang.liquidacion_pagos",
    destacado: true,
  },
  {
    sku: "intang.recuperador_fiscal",
    nombre: "Recuperador de Retenciones AFIP",
    lema: "Percepciones olvidadas = plata tirada.",
    tipo: "intangible",
    nicho: "protege",
    remotoDesdeCasa: true,
    vibeTags: ["afip", "retenciones", "percepciones", "iibb", "apocrifo", "fiscal"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 18900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-25",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 45,
    descripcionCorta:
      "Bot fiscal: padrones diarios, cruce con compras, crédito pre-cargado y bloqueo de proveedores apócrifos.",
    playbookId: "playbook.intang.recuperador_fiscal",
    destacado: true,
  },
  {
    sku: "intang.guardian_pos",
    nombre: "Guardián de Caja POS",
    lema: "Robo hormiga detectado antes del arqueo.",
    tipo: "intangible",
    nicho: "protege",
    remotoDesdeCasa: true,
    vibeTags: ["pos", "fraude", "anulaciones", "caja", "auditoria", "seguridad"],
    autoCertLevel: "REGION_AUTO",
    precioDesdeArs: 14900,
    tipoCobro: "mensual",
    maturity: "growing",
    poolSince: "2026-06-25",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 10,
    descripcionCorta:
      "Score de riesgo diario: anulaciones, devoluciones y egresos sospechosos. Reporte WhatsApp al dueño.",
    playbookId: "playbook.intang.guardian_pos",
    destacado: true,
  },
  {
    sku: "intang.reponedor_jit",
    nombre: "Reponedor JIT",
    lema: "Ni quiebre ni capital muerto.",
    tipo: "intangible",
    nicho: "ordena",
    remotoDesdeCasa: true,
    vibeTags: ["stock", "compras", "jit", "quiebre", "reposicion", "sap"],
    autoCertLevel: "REGION_AUTO",
    precioDesdeArs: 16900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-25",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 20,
    descripcionCorta:
      "Velocidad de venta + lead time → propuestas de OC y mails de cotización pre-redactados.",
    playbookId: "playbook.intang.reponedor_jit",
    destacado: true,
  },
  {
    sku: "intang.ocr_compras",
    nombre: "OCR Compras Proveedores",
    lema: "La foto reemplaza tres horas de carga.",
    tipo: "intangible",
    nicho: "carga",
    remotoDesdeCasa: true,
    vibeTags: ["ocr", "compras", "proveedores", "pdf", "gemini", "odoo"],
    autoCertLevel: "SEMI_AUTO",
    precioDesdeArs: 9900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-25",
    poolVersion: "1.0.0",
    impactoUniversal: 5,
    activacionMinutos: 15,
    descripcionCorta:
      "Reenviá facturas a compras@claver.com. IA mapea ítems del proveedor con tu catálogo ERP.",
    playbookId: "playbook.intang.ocr_compras",
    destacado: true,
  },
  {
    sku: "intang.ruteador_entregas",
    nombre: "Ruteador de Entregas",
    lema: "El cliente deja de llamar. El chofer deja de dar vueltas.",
    tipo: "intangible",
    nicho: "ordena",
    remotoDesdeCasa: true,
    vibeTags: ["logistica", "ruteo", "whatsapp", "entregas", "gps", "bringg"],
    autoCertLevel: "REGION_AUTO",
    precioDesdeArs: 19900,
    tipoCobro: "mensual",
    maturity: "seed",
    poolSince: "2026-06-25",
    poolVersion: "1.0.0",
    impactoUniversal: 4,
    activacionMinutos: 40,
    descripcionCorta:
      "Ruta óptima por zona + notificación WA al cliente cuando el chofer inicia con link de seguimiento.",
    playbookId: "playbook.intang.ruteador_entregas",
  },
]

export function getAutopoolByTipo(tipo: AutopoolTipoId): AutopoolEntry[] {
  return AUTOPOOL_ENTRIES.filter((e) => e.tipo === tipo)
}

export function getAutopoolByNicho(nicho: AutopoolNichoId): AutopoolEntry[] {
  return AUTOPOOL_ENTRIES.filter((e) => e.nicho === nicho)
}

export function getAutopoolRemotos(): AutopoolEntry[] {
  return AUTOPOOL_ENTRIES.filter((e) => e.remotoDesdeCasa)
}

export function getAutopoolDestacados(): AutopoolEntry[] {
  return AUTOPOOL_ENTRIES.filter((e) => e.destacado)
}

export function detectAutopoolNicho(query: string): AutopoolNichoId | null {
  const q = query.toLowerCase()
  for (const [id, n] of Object.entries(AUTOPOOL_NICHOS)) {
    if (q.includes(n.label.toLowerCase()) || q.includes(id)) return id as AutopoolNichoId
  }
  const hit = AUTOPOOL_ENTRIES.find(
    (e) =>
      e.vibeTags.some((t) => q.includes(t)) ||
      e.lema.toLowerCase().includes(q) ||
      e.nombre.toLowerCase().includes(q)
  )
  return hit?.nicho ?? null
}

/**
 * Plantilla — copiar al agregar servicio nuevo (vibe coding diario)
 *
 * {
 *   sku: "categoria.nombre",
 *   nombre: "Nombre Comercial",
 *   lema: "Una línea que vende.",
 *   nicho: "avisa",
 *   vibeTags: ["tag1", "automatico"],
 *   autoCertLevel: "GLOBAL_AUTO",
 *   precioDesdeArs: 2990,
 *   tipoCobro: "mensual",
 *   maturity: "seed",
 *   poolSince: "2026-06-25",
 *   poolVersion: "1.0.0",
 *   impactoUniversal: 4,
 *   activacionMinutos: 5,
 *   descripcionCorta: "...",
 *   playbookId: "playbook.categoria.nombre",
 * },
 */
export const AUTOPOOL_ENTRY_TEMPLATE = {
  sku: "categoria.nombre",
  nombre: "Nombre Comercial",
  lema: "Una línea que vende.",
  tipo: "automation" as AutopoolTipoId,
  nicho: "avisa" as AutopoolNichoId,
  integracionId: undefined,
  remotoDesdeCasa: true,
  vibeTags: ["tag1", "automatico"],
  autoCertLevel: "GLOBAL_AUTO" as AutopoolCertLevel,
  precioDesdeArs: 2990,
  tipoCobro: "mensual" as const,
  maturity: "seed" as AutopoolMaturity,
  poolSince: "YYYY-MM-DD",
  poolVersion: "1.0.0",
  impactoUniversal: 4 as const,
  activacionMinutos: 5,
  descripcionCorta: "Qué hace en una oración.",
  playbookId: "playbook.categoria.nombre",
} as const