import { RETAIL_EXTENSION_CATALOG } from "./retail-extension-catalog"

export type AutoCertLevel = "GLOBAL_AUTO" | "REGION_AUTO" | "SEMI_AUTO" | "HUMAN_GATE"

export interface MarketplaceSku {
  sku: string
  nombre: string
  categoria: string
  precioArs: number
  tipoCobro: "recurrente" | "por_uso"
  autoCertLevel: AutoCertLevel
  paisesHabilitados: string[]
  i18n: Record<string, { nombre: string; descripcion: string; packOnboardSubject: string }>
  segmentoAds: string[]
  playbookId?: string
  dependeDe?: string[]
  status: "disponible" | "beta" | "planned"
  trialDias?: number
}

// 45 Servicios listados en el prompt
export const MARKETPLACE_CATALOG: MarketplaceSku[] = [
  // --- Seguridad ---
  {
    sku: "sec.vpn_corp",
    nombre: "VPN Corporativa",
    categoria: "Seguridad",
    precioArs: 15000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "VPN Corporativa", descripcion: "Acceso remoto seguro", packOnboardSubject: "Tus credenciales VPN" } },
    segmentoAds: ["distribuidora", "salud"],
    playbookId: "playbook.sec.vpn_corp",
    status: "disponible",
    trialDias: 14,
  },
  {
    sku: "sec.dns_filter",
    nombre: "Filtro DNS",
    categoria: "Seguridad",
    precioArs: 8000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Filtro DNS", descripcion: "Bloqueo de amenazas por DNS", packOnboardSubject: "Configuración DNS" } },
    segmentoAds: ["general"],
    playbookId: "playbook.sec.dns_filter",
    status: "disponible",
  },
  {
    sku: "sec.ssl_auto",
    nombre: "SSL Automático",
    categoria: "Seguridad",
    precioArs: 5000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "SSL Automático", descripcion: "Certificados SSL administrados", packOnboardSubject: "Tu certificado SSL está listo" } },
    segmentoAds: ["ecommerce"],
    playbookId: "playbook.sec.ssl_auto",
    status: "disponible",
  },
  {
    sku: "sec.mfa",
    nombre: "Autenticación MFA",
    categoria: "Seguridad",
    precioArs: 7000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "MFA", descripcion: "Doble factor de autenticación", packOnboardSubject: "Activación MFA" } },
    segmentoAds: ["general"],
    playbookId: "playbook.sec.mfa",
    status: "disponible",
  },
  {
    sku: "sec.backup",
    nombre: "Backup Cloud",
    categoria: "Seguridad",
    precioArs: 20000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Backup Cloud", descripcion: "Respaldo automático de base de datos", packOnboardSubject: "Tus backups están configurados" } },
    segmentoAds: ["general"],
    playbookId: "playbook.sec.backup",
    status: "disponible",
  },
  {
    sku: "sec.edr",
    nombre: "EDR Ligero",
    categoria: "Seguridad",
    precioArs: 25000,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "EDR", descripcion: "Protección de endpoints", packOnboardSubject: "Instalá tu agente EDR" } },
    segmentoAds: ["general"],
    playbookId: "playbook.sec.edr",
    status: "disponible",
  },
  {
    sku: "sec.vault",
    nombre: "Gestor de Contraseñas",
    categoria: "Seguridad",
    precioArs: 10000,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "Bóveda de claves", descripcion: "Gestor de contraseñas seguro", packOnboardSubject: "Invitación a tu bóveda" } },
    segmentoAds: ["general"],
    playbookId: "playbook.sec.vault",
    status: "disponible",
  },
  {
    sku: "sec.vpn_site",
    nombre: "Túnel Sucursal",
    categoria: "Seguridad",
    precioArs: 30000,
    tipoCobro: "recurrente",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "VPN Sucursal", descripcion: "Túnel seguro entre sucursales", packOnboardSubject: "Instrucciones de túnel" } },
    segmentoAds: ["distribuidora"],
    playbookId: "playbook.sec.vpn_site",
    status: "disponible",
  },

  // --- Infraestructura ---
  {
    sku: "infra.uptime",
    nombre: "Monitoreo Uptime",
    categoria: "Infraestructura",
    precioArs: 5000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Uptime", descripcion: "Monitoreo HTTP continuo", packOnboardSubject: "Tu Status Page" } },
    segmentoAds: ["ecommerce"],
    playbookId: "playbook.infra.uptime",
    status: "disponible",
  },
  {
    sku: "infra.email",
    nombre: "Email Corporativo",
    categoria: "Infraestructura",
    precioArs: 12000,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "Email Corporativo", descripcion: "Casillas de mail empresariales", packOnboardSubject: "Configuración de tu correo" } },
    segmentoAds: ["general"],
    playbookId: "playbook.infra.email",
    status: "disponible",
  },
  {
    sku: "infra.dominio",
    nombre: "Dominio + DNS",
    categoria: "Infraestructura",
    precioArs: 15000,
    tipoCobro: "recurrente",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "Dominio Web", descripcion: "Registro de dominio y gestión DNS", packOnboardSubject: "Gestión de dominio" } },
    segmentoAds: ["ecommerce"],
    playbookId: "playbook.infra.dominio",
    status: "disponible",
  },
  {
    sku: "infra.landing",
    nombre: "Landing por Rubro",
    categoria: "Infraestructura",
    precioArs: 18000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Landing Page", descripcion: "Página web autogenerada", packOnboardSubject: "Tu landing está online" } },
    segmentoAds: ["general"],
    playbookId: "playbook.infra.landing",
    status: "disponible",
  },
  {
    sku: "infra.cdn",
    nombre: "CDN Global",
    categoria: "Infraestructura",
    precioArs: 9000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "CDN", descripcion: "Aceleración web global", packOnboardSubject: "Tu CDN está activo" } },
    segmentoAds: ["ecommerce"],
    playbookId: "playbook.infra.cdn",
    status: "disponible",
  },
  {
    sku: "infra.storage",
    nombre: "Almacenamiento S3",
    categoria: "Infraestructura",
    precioArs: 10000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Almacenamiento", descripcion: "Bucket privado en la nube", packOnboardSubject: "Credenciales de Storage" } },
    segmentoAds: ["general"],
    playbookId: "playbook.infra.storage",
    status: "disponible",
  },
  {
    sku: "infra.remote",
    nombre: "Soporte Remoto",
    categoria: "Infraestructura",
    precioArs: 6000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Soporte Remoto", descripcion: "Software de acceso remoto", packOnboardSubject: "Enlace de asistencia remota" } },
    segmentoAds: ["general"],
    playbookId: "playbook.infra.remote",
    status: "disponible",
  },
  {
    sku: "infra.mdm",
    nombre: "Gestión MDM",
    categoria: "Infraestructura",
    precioArs: 25000,
    tipoCobro: "recurrente",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "MDM", descripcion: "Gestión de dispositivos móviles", packOnboardSubject: "Instrucciones de Enrollment" } },
    segmentoAds: ["distribuidora"],
    playbookId: "playbook.infra.mdm",
    status: "disponible",
  },

  // --- Comunicaciones ---
  {
    sku: "com.whatsapp",
    nombre: "WhatsApp Business API",
    categoria: "Comunicaciones",
    precioArs: 15000,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "WhatsApp API", descripcion: "Integración oficial WhatsApp", packOnboardSubject: "Tu canal de WhatsApp" } },
    segmentoAds: ["ecommerce", "salud"],
    playbookId: "playbook.com.whatsapp",
    status: "disponible",
  },
  {
    sku: "com.sms",
    nombre: "SMS Transaccional",
    categoria: "Comunicaciones",
    precioArs: 5000,
    tipoCobro: "por_uso",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "SMS", descripcion: "Envío de alertas SMS", packOnboardSubject: "Servicio SMS activo" } },
    segmentoAds: ["salud", "ecommerce"],
    playbookId: "playbook.com.sms",
    status: "disponible",
  },
  {
    sku: "com.email_tx",
    nombre: "Email Transaccional",
    categoria: "Comunicaciones",
    precioArs: 8000,
    tipoCobro: "por_uso",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "Email Dedicado", descripcion: "Envío de correos transaccionales", packOnboardSubject: "Credenciales SMTP" } },
    segmentoAds: ["ecommerce"],
    playbookId: "playbook.com.email_tx",
    status: "disponible",
  },
  {
    sku: "com.ivr",
    nombre: "Central Virtual IVR",
    categoria: "Comunicaciones",
    precioArs: 20000,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "IVR Telefónico", descripcion: "Centralita con menú de voz", packOnboardSubject: "Tu número virtual" } },
    segmentoAds: ["general"],
    playbookId: "playbook.com.ivr",
    status: "disponible",
  },
  {
    sku: "com.chat",
    nombre: "Chat Widget + IA",
    categoria: "Comunicaciones",
    precioArs: 18000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Web Chat", descripcion: "Widget de chat para tu web", packOnboardSubject: "Código de integración del Chat" } },
    segmentoAds: ["ecommerce"],
    playbookId: "playbook.com.chat",
    status: "disponible",
  },
  {
    sku: "com.video",
    nombre: "Videoconferencia Branded",
    categoria: "Comunicaciones",
    precioArs: 15000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Videoconferencia", descripcion: "Salas de reuniones virtuales", packOnboardSubject: "Tu sala de reuniones lista" } },
    segmentoAds: ["salud", "servicios"],
    playbookId: "playbook.com.video",
    status: "disponible",
  },

  // --- Fiscal & Legal ---
  {
    sku: "fiscal.firma",
    nombre: "Firma Electrónica",
    categoria: "Fiscal",
    precioArs: 10000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Firma Digital", descripcion: "Gestión de contratos y firmas", packOnboardSubject: "Portal de firmas" } },
    segmentoAds: ["general"],
    playbookId: "playbook.fiscal.firma",
    status: "disponible",
  },
  {
    sku: "fiscal.cert_afip",
    nombre: "Certificado AFIP",
    categoria: "Fiscal",
    precioArs: 5000,
    tipoCobro: "recurrente",
    autoCertLevel: "HUMAN_GATE",
    paisesHabilitados: ["AR"],
    i18n: { "es-AR": { nombre: "Certificado AFIP", descripcion: "Homologación fiscal", packOnboardSubject: "Instrucciones de AFIP" } },
    segmentoAds: ["general"],
    playbookId: "playbook.fiscal.cert_afip",
    status: "disponible",
  },
  {
    sku: "fiscal.ocr",
    nombre: "OCR Facturas de Compra",
    categoria: "Fiscal",
    precioArs: 12000,
    tipoCobro: "por_uso",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Lectura OCR", descripcion: "Extracción de datos con IA", packOnboardSubject: "El módulo OCR está activo" } },
    segmentoAds: ["contador"],
    playbookId: "playbook.fiscal.ocr",
    status: "disponible",
  },
  {
    sku: "fiscal.conciliacion",
    nombre: "Conciliación Bancaria",
    categoria: "Fiscal",
    precioArs: 9000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Conciliación", descripcion: "Conciliación automática CSV", packOnboardSubject: "Módulo de conciliación" } },
    segmentoAds: ["contador", "general"],
    playbookId: "playbook.fiscal.conciliacion",
    status: "disponible",
  },
  {
    sku: "fiscal.clavpay_link",
    nombre: "Links de Cobro",
    categoria: "Fiscal",
    precioArs: 6000,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "Links de Pago", descripcion: "Cobros por enlace", packOnboardSubject: "Generá tu primer link" } },
    segmentoAds: ["ecommerce"],
    playbookId: "playbook.fiscal.clavpay_link",
    status: "disponible",
  },
  {
    sku: "fiscal.recordatorios",
    nombre: "Recordatorios Vencimientos",
    categoria: "Fiscal",
    precioArs: 4000,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "Alertas Fiscales", descripcion: "Calendario de impuestos", packOnboardSubject: "Tus recordatorios impositivos" } },
    segmentoAds: ["contador"],
    playbookId: "playbook.fiscal.recordatorios",
    status: "disponible",
  },
  {
    sku: "fiscal.scoring",
    nombre: "Scoring Crediticio",
    categoria: "Fiscal",
    precioArs: 15000,
    tipoCobro: "por_uso",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "Veraz/Scoring", descripcion: "Reportes crediticios automáticos", packOnboardSubject: "Consultas de Scoring" } },
    segmentoAds: ["distribuidora", "agro"],
    playbookId: "playbook.fiscal.scoring",
    status: "disponible",
  },

  // --- Operaciones ---
  {
    sku: "ops.gps",
    nombre: "GPS y Flota",
    categoria: "Operaciones",
    precioArs: 12000,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "GPS Flota", descripcion: "Seguimiento de vehículos", packOnboardSubject: "Panel de control GPS" } },
    segmentoAds: ["distribuidora", "agro"],
    playbookId: "playbook.ops.gps",
    status: "disponible",
  },
  {
    sku: "ops.iot_kit",
    nombre: "Kit Sensores IoT",
    categoria: "Operaciones",
    precioArs: 25000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Sensores IoT", descripcion: "Ingesta de datos MQTT", packOnboardSubject: "Credenciales MQTT" } },
    segmentoAds: ["agro", "industria"],
    playbookId: "playbook.ops.iot_kit",
    status: "disponible",
  },
  {
    sku: "ops.qr_trace",
    nombre: "Trazabilidad QR",
    categoria: "Operaciones",
    precioArs: 8000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "QR Trazabilidad", descripcion: "Etiquetas y escaneo", packOnboardSubject: "Imprimí tus QRs" } },
    segmentoAds: ["industria"],
    playbookId: "playbook.ops.qr_trace",
    status: "disponible",
  },
  {
    sku: "ops.device_agent",
    nombre: "Agente Balanzas/Impresoras",
    categoria: "Operaciones",
    precioArs: 7000,
    tipoCobro: "recurrente",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Agente Hardware", descripcion: "Conector USB/COM local", packOnboardSubject: "Instalá el agente local" } },
    segmentoAds: ["general"],
    playbookId: "playbook.ops.device_agent",
    status: "disponible",
  },
  {
    sku: "ops.menu_qr",
    nombre: "Menú Digital QR",
    categoria: "Operaciones",
    precioArs: 6000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Menú QR", descripcion: "Catálogo en el salón", packOnboardSubject: "QRs de tus mesas" } },
    segmentoAds: ["restaurante"],
    playbookId: "playbook.ops.menu_qr",
    status: "disponible",
  },
  {
    sku: "ops.agenda_web",
    nombre: "Agenda Online Pública",
    categoria: "Operaciones",
    precioArs: 5000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Turnos Web", descripcion: "Reservas de turnos 24/7", packOnboardSubject: "El enlace de tu agenda" } },
    segmentoAds: ["salud", "servicios"],
    playbookId: "playbook.ops.agenda_web",
    status: "disponible",
  },

  // --- Datos, IA & MKT ---
  {
    sku: "data.bi",
    nombre: "Tableros BI",
    categoria: "Datos",
    precioArs: 18000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Tableros BI", descripcion: "Inteligencia de negocios", packOnboardSubject: "Tus dashboards BI" } },
    segmentoAds: ["contador", "general"],
    playbookId: "playbook.data.bi",
    status: "disponible",
  },
  {
    sku: "data.reportes_prog",
    nombre: "Reportes Programados",
    categoria: "Datos",
    precioArs: 6000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Reportes Auto", descripcion: "Reportes en tu bandeja", packOnboardSubject: "Reportes matutinos activos" } },
    segmentoAds: ["general"],
    playbookId: "playbook.data.reportes_prog",
    status: "disponible",
  },
  {
    sku: "data.nps",
    nombre: "Encuestas NPS",
    categoria: "Datos",
    precioArs: 4000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "NPS", descripcion: "Mide la satisfacción", packOnboardSubject: "Encuestas habilitadas" } },
    segmentoAds: ["ecommerce"],
    playbookId: "playbook.data.nps",
    status: "disponible",
  },
  {
    sku: "data.helpdesk_ia",
    nombre: "Helpdesk IA 1ra Línea",
    categoria: "Datos",
    precioArs: 15000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Agente Soporte IA", descripcion: "Respuestas automáticas de tickets", packOnboardSubject: "El agente IA está listo" } },
    segmentoAds: ["ecommerce", "distribuidora"],
    playbookId: "playbook.data.helpdesk_ia",
    status: "disponible",
  },
  {
    sku: "data.lms",
    nombre: "Micro LMS Capacitación",
    categoria: "Datos",
    precioArs: 12000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "LMS Interno", descripcion: "Cursos para empleados", packOnboardSubject: "Portal de capacitación" } },
    segmentoAds: ["servicios"],
    playbookId: "playbook.data.lms",
    status: "disponible",
  },
  {
    sku: "mkt.gbp",
    nombre: "Google Business Sync",
    categoria: "Marketing",
    precioArs: 4000,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "US"],
    i18n: { "es-AR": { nombre: "Google Maps", descripcion: "Sincroniza tus sucursales", packOnboardSubject: "Conecta Google Business" } },
    segmentoAds: ["restaurante", "salud"],
    playbookId: "playbook.mkt.gbp",
    status: "disponible",
  },
  {
    sku: "mkt.catalogo_pdf",
    nombre: "Catálogo Automático PDF",
    categoria: "Marketing",
    precioArs: 5000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Catálogo PDF", descripcion: "Exporta tus productos listos para WhatsApp", packOnboardSubject: "Descargá tus catálogos" } },
    segmentoAds: ["distribuidora", "ecommerce"],
    playbookId: "playbook.mkt.catalogo_pdf",
    status: "disponible",
  },
  {
    sku: "mkt.pixel",
    nombre: "Pixels Tracking (Meta/GA4)",
    categoria: "Marketing",
    precioArs: 3000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Pixels Ad", descripcion: "Inyecta scripts de conversión", packOnboardSubject: "Pixels en línea" } },
    segmentoAds: ["ecommerce"],
    playbookId: "playbook.mkt.pixel",
    status: "disponible",
  },
  {
    sku: "mkt.giftcard",
    nombre: "Gift Cards Digitales",
    categoria: "Marketing",
    precioArs: 7000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Vouchers", descripcion: "Venta de tarjetas de regalo", packOnboardSubject: "Vouchers activos" } },
    segmentoAds: ["restaurante", "salud"],
    playbookId: "playbook.mkt.giftcard",
    status: "disponible",
  },
  {
    sku: "mkt.referidos",
    nombre: "Programa de Referidos",
    categoria: "Marketing",
    precioArs: 10000,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["*"],
    i18n: { "es-AR": { nombre: "Referidos", descripcion: "Gestión de referidos en billetera", packOnboardSubject: "Wallet de referidos" } },
    segmentoAds: ["ecommerce"],
    playbookId: "playbook.mkt.referidos",
    status: "disponible",
  },

  // --- Libreta Fiado (almacenes de barrio) ---
  {
    sku: "pos.fiado_barrio",
    nombre: "Libreta Fiado",
    categoria: "Intangibles",
    precioArs: 4990,
    tipoCobro: "recurrente",
    autoCertLevel: "GLOBAL_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Libreta Fiado",
        descripcion: "Fiá con límite y avisá por email qué compró cada cliente",
        packOnboardSubject: "Tu libreta digital ya está activa",
      },
    },
    segmentoAds: ["kiosco", "almacen", "barrio"],
    playbookId: "playbook.pos.fiado_barrio",
    status: "disponible",
    trialDias: 14,
  },

  // --- Servicios intangibles (Top 5 — bolsillo + ansiedad) ---
  {
    sku: "intang.cobranzas_wa",
    nombre: "Secretaria de Cobranzas WA",
    categoria: "Intangibles",
    precioArs: 20000,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "UY"],
    i18n: {
      "es-AR": {
        nombre: "Secretaria de Cobranzas WA",
        descripcion: "WhatsApp automático a deudores con saldo del ERP y link de pago",
        packOnboardSubject: "Tu secretaria de cobranzas ya está activa",
      },
    },
    segmentoAds: ["distribuidora", "pyme", "servicios"],
    playbookId: "playbook.intang.cobranzas_wa",
    dependeDe: ["com.whatsapp"],
    status: "disponible",
    trialDias: 7,
  },
  {
    sku: "intang.reputation_firewall",
    nombre: "Escudo Reputación",
    categoria: "Intangibles",
    precioArs: 14900,
    tipoCobro: "recurrente",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["*"],
    i18n: {
      "es-AR": {
        nombre: "Escudo Reputación",
        descripcion: "Alerta crisis en reseñas 1★ y respuesta IA conciliadora",
        packOnboardSubject: "Tu firewall de reputación está en línea",
      },
    },
    segmentoAds: ["restaurante", "hotel", "salud", "retail"],
    playbookId: "playbook.intang.reputation_firewall",
    status: "disponible",
    trialDias: 14,
  },
  {
    sku: "intang.legal_shield",
    nombre: "Legal Shield",
    categoria: "Intangibles",
    precioArs: 9900,
    tipoCobro: "recurrente",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["AR", "MX", "ES"],
    i18n: {
      "es-AR": {
        nombre: "Legal Shield",
        descripcion: "Escáner de contratos PDF con semáforo legal en 30 segundos",
        packOnboardSubject: "Enviá tu primer contrato a legal@claver.com",
      },
    },
    segmentoAds: ["general", "inmobiliaria", "pyme"],
    playbookId: "playbook.intang.legal_shield",
    status: "disponible",
    trialDias: 3,
  },
  {
    sku: "intang.subs_tax_scanner",
    nombre: "Cazador de Gastos Zombies",
    categoria: "Intangibles",
    precioArs: 3000,
    tipoCobro: "recurrente",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Cazador de Gastos Zombies",
        descripcion: "Detectá suscripciones al pedo e impuestos de más en tu resumen",
        packOnboardSubject: "Conectá tu primer resumen y empezá a ahorrar",
      },
    },
    segmentoAds: ["b2c", "consumidor"],
    playbookId: "playbook.intang.subs_tax_scanner",
    status: "beta",
    trialDias: 14,
  },
  {
    sku: "intang.reactivador_clientes",
    nombre: "Despertador de Clientes",
    categoria: "Intangibles",
    precioArs: 12900,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "UY"],
    i18n: {
      "es-AR": {
        nombre: "Despertador de Clientes",
        descripcion: "Reactivá clientes dormidos con WA/SMS hiper-personalizado y ROI visible",
        packOnboardSubject: "Tu primera campaña de reactivación está lista",
      },
    },
    segmentoAds: ["ecommerce", "retail", "distribuidora"],
    playbookId: "playbook.intang.reactivador_clientes",
    dependeDe: ["com.whatsapp"],
    status: "disponible",
    trialDias: 7,
  },

  // --- Servicios intangibles Premium 7 (SAP/Odoo/Salesforce adaptados AR) ---
  {
    sku: "intang.liquidacion_pagos",
    nombre: "Conciliador Liquidación MP y Tarjetas",
    categoria: "Intangibles",
    precioArs: 24900,
    tipoCobro: "recurrente",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Conciliador Liquidación MP y Tarjetas",
        descripcion: "Cruza ventas POS con liquidaciones MP/Prisma/MODO y alerta comisiones fantasmas",
        packOnboardSubject: "Tu conciliador de pagos está activo",
      },
    },
    segmentoAds: ["retail", "restaurante", "pyme"],
    playbookId: "playbook.intang.liquidacion_pagos",
    dependeDe: ["channel.mercadopago"],
    status: "beta",
    trialDias: 14,
  },
  {
    sku: "intang.recuperador_fiscal",
    nombre: "Auditor Tributario y Recuperador de Retenciones",
    categoria: "Intangibles",
    precioArs: 18900,
    tipoCobro: "recurrente",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Recuperador de Retenciones AFIP",
        descripcion: "Extrae padrones, cruza compras y pre-carga créditos fiscales; bloquea apócrifos",
        packOnboardSubject: "Conectá tu clave fiscal para recuperar retenciones",
      },
    },
    segmentoAds: ["pyme", "distribuidora", "industria"],
    playbookId: "playbook.intang.recuperador_fiscal",
    status: "beta",
    trialDias: 7,
  },
  {
    sku: "intang.guardian_pos",
    nombre: "Guardián de Caja y Auditor de Fraude POS",
    categoria: "Intangibles",
    precioArs: 14900,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "UY"],
    i18n: {
      "es-AR": {
        nombre: "Guardián de Caja POS",
        descripcion: "Reporte diario de riesgo: anulaciones, devoluciones y egresos sospechosos",
        packOnboardSubject: "Tu auditor de caja POS está en línea",
      },
    },
    segmentoAds: ["retail", "kiosco", "restaurante"],
    playbookId: "playbook.intang.guardian_pos",
    dependeDe: ["core.pos"],
    status: "disponible",
    trialDias: 7,
  },
  {
    sku: "intang.reponedor_jit",
    nombre: "Reponedor Inteligente Just-In-Time",
    categoria: "Intangibles",
    precioArs: 16900,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR", "MX", "UY"],
    i18n: {
      "es-AR": {
        nombre: "Reponedor JIT",
        descripcion: "Propuestas de compra según velocidad de venta, stock mínimo y lead time",
        packOnboardSubject: "Tu reponedor inteligente ya calcula quiebres",
      },
    },
    segmentoAds: ["retail", "distribuidora", "almacen"],
    playbookId: "playbook.intang.reponedor_jit",
    status: "beta",
    trialDias: 14,
  },
  {
    sku: "intang.ocr_compras",
    nombre: "Importador Inteligente de Facturas de Proveedores",
    categoria: "Intangibles",
    precioArs: 9900,
    tipoCobro: "por_uso",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "OCR Compras Proveedores",
        descripcion: "Reenviá PDF/XML a compras@claver.com — IA pre-carga la orden de compra",
        packOnboardSubject: "Tu buzón de compras inteligente está listo",
      },
    },
    segmentoAds: ["pyme", "distribuidora", "industria"],
    playbookId: "playbook.intang.ocr_compras",
    dependeDe: ["fiscal.ocr"],
    status: "beta",
    trialDias: 7,
  },
  {
    sku: "intang.ruteador_entregas",
    nombre: "Ruteador Logístico y Notificador de Entregas",
    categoria: "Intangibles",
    precioArs: 19900,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Ruteador de Entregas",
        descripcion: "Ruta óptima + WhatsApp al cliente cuando el chofer sale con link de seguimiento",
        packOnboardSubject: "Tu ruteador logístico está en cola de activación",
      },
    },
    segmentoAds: ["distribuidora", "logistica", "ecommerce"],
    playbookId: "playbook.intang.ruteador_entregas",
    dependeDe: ["com.whatsapp"],
    status: "planned",
    trialDias: 14,
  },

  // --- Pack Almacén Rosario (retail barrio) ---
  {
    sku: "pos.margen_guard",
    nombre: "Guardián de Margen POS",
    categoria: "Operaciones",
    precioArs: 3990,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Guardián de Margen POS",
        descripcion: "Bloquea o ajusta precios cuando el costo de lista supera la góndola",
        packOnboardSubject: "Tu margen está protegido en caja",
      },
    },
    segmentoAds: ["kiosco", "almacen", "retail"],
    playbookId: "playbook.pos.margen_guard",
    dependeDe: ["core.pos"],
    status: "disponible",
    trialDias: 7,
  },
  {
    sku: "pos.zero_waste",
    nombre: "Zero Waste Bot",
    categoria: "Operaciones",
    precioArs: 5990,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Zero Waste Bot",
        descripcion: "Descuentos automáticos por vencimiento y remate verdulería tarde",
        packOnboardSubject: "Menos merma, más caja",
      },
    },
    segmentoAds: ["almacen", "fiambreria", "verduleria"],
    playbookId: "playbook.pos.zero_waste",
    dependeDe: ["core.pos"],
    status: "disponible",
    trialDias: 7,
  },
  {
    sku: "pos.stock_cero_alert",
    nombre: "Alerta Stock Cero",
    categoria: "Operaciones",
    precioArs: 2990,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Alerta Stock Cero",
        descripcion: "Vende igual y avisa al dueño cuando el stock figuraba en cero",
        packOnboardSubject: "Robo hormiga bajo control",
      },
    },
    segmentoAds: ["kiosco", "almacen"],
    playbookId: "playbook.pos.stock_cero_alert",
    dependeDe: ["core.pos"],
    status: "disponible",
    trialDias: 7,
  },
  {
    sku: "pos.promos_pago",
    nombre: "Copiloto Promos Medios de Pago",
    categoria: "Operaciones",
    precioArs: 2990,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Copiloto Promos MP/MODO/BSF",
        descripcion: "Calendario de promos bancarias en el POS al momento del cobro",
        packOnboardSubject: "Que el cajero no se olvide del reintegro",
      },
    },
    segmentoAds: ["almacen", "retail"],
    playbookId: "playbook.pos.promos_pago",
    dependeDe: ["core.pos"],
    status: "disponible",
    trialDias: 7,
  },
  {
    sku: "pos.lista_distribuidora",
    nombre: "Importador Listas Distribuidoras",
    categoria: "Operaciones",
    precioArs: 4990,
    tipoCobro: "recurrente",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Importador Listas Rosario",
        descripcion: "CSV de Micropack/Vital/Makro → precios POS con margen histórico",
        packOnboardSubject: "Subí la lista y listo",
      },
    },
    segmentoAds: ["almacen", "autoservicio"],
    playbookId: "playbook.pos.lista_distribuidora",
    dependeDe: ["core.pos"],
    status: "beta",
    trialDias: 14,
  },
  {
    sku: "pos.panico_vecinal",
    nombre: "Botón Pánico Vecinal",
    categoria: "Seguridad",
    precioArs: 1990,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Botón Pánico Vecinal",
        descripcion: "Alerta silenciosa por WhatsApp a vecinos comerciantes desde el POS",
        packOnboardSubject: "Tu red de almaceneros conectada",
      },
    },
    segmentoAds: ["almacen", "kiosco"],
    playbookId: "playbook.pos.panico_vecinal",
    dependeDe: ["core.pos", "com.whatsapp"],
    status: "disponible",
    trialDias: 7,
  },
  {
    sku: "pos.envases_gaseosas",
    nombre: "Envases de Gaseosas",
    categoria: "Operaciones",
    precioArs: 2490,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Préstamo de Envases",
        descripcion: "Cajones Coca/Sprite retornables con depósito en caja desde el POS",
        packOnboardSubject: "Controlá los cajones que salen del local",
      },
    },
    segmentoAds: ["almacen", "kiosco", "distribuidora"],
    playbookId: "playbook.pos.envases_gaseosas",
    dependeDe: ["core.pos"],
    status: "disponible",
    trialDias: 7,
  },
  {
    sku: "pos.vale_dinero",
    nombre: "Vale de Dinero",
    categoria: "Operaciones",
    precioArs: 1990,
    tipoCobro: "recurrente",
    autoCertLevel: "REGION_AUTO",
    paisesHabilitados: ["AR"],
    i18n: {
      "es-AR": {
        nombre: "Ticket Vale de Dinero",
        descripcion: "Emití vales canjeables en POS con ticket impreso y cobro parcial",
        packOnboardSubject: "Vales para cambios y devoluciones en el mostrador",
      },
    },
    segmentoAds: ["almacen", "kiosco"],
    playbookId: "playbook.pos.vale_dinero",
    dependeDe: ["core.pos"],
    status: "disponible",
    trialDias: 7,
  },

  // --- Claver Cloud Ops (Enterprise) ---
  {
    sku: "ops.claver_superadmin",
    nombre: "Claver Super Admin Panel",
    categoria: "Claver Cloud",
    precioArs: 0,
    tipoCobro: "recurrente",
    autoCertLevel: "HUMAN_GATE",
    paisesHabilitados: ["*"],
    i18n: {
      "es-AR": {
        nombre: "Super Admin Panel",
        descripcion: "Gobernanza multi-tenant: catálogo SKUs, readiness, impersonación ERP y dashboard de flota",
        packOnboardSubject: "Tu consola super administrador está lista",
      },
    },
    segmentoAds: ["enterprise", "implementacion"],
    playbookId: "playbook.ops.claver_superadmin",
    status: "disponible",
  },
  {
    sku: "ops.playbooks_auto",
    nombre: "Playbooks ejecución automática",
    categoria: "Claver Cloud",
    precioArs: 14900,
    tipoCobro: "recurrente",
    autoCertLevel: "HUMAN_GATE",
    paisesHabilitados: ["*"],
    i18n: {
      "es-AR": {
        nombre: "Playbooks automáticos",
        descripcion: "Botones de secuencias ops: health, snapshot VAL, packs enganche, backup",
        packOnboardSubject: "Automatizaciones Claver Cloud activadas",
      },
    },
    segmentoAds: ["enterprise", "implementacion"],
    playbookId: "playbook.ops.playbooks_auto",
    dependeDe: ["ops.claver_superadmin"],
    status: "disponible",
  },

  {
    sku: "bridge.opo_studio",
    nombre: "OPO Studio Bridge",
    categoria: "Integraciones",
    precioArs: 24900,
    tipoCobro: "recurrente",
    autoCertLevel: "SEMI_AUTO",
    paisesHabilitados: ["AR", "BR"],
    i18n: {
      "es-AR": {
        nombre: "OPO Studio Bridge",
        descripcion:
          "Capa semántica sobre Protheus o Clavis: ontología, introspección REST/SQL y playground IA",
        packOnboardSubject: "Tu puente OPO está listo — conectá legacy en minutos",
      },
    },
    segmentoAds: ["erp", "protheus", "digitalizacion"],
    playbookId: "playbook.bridge.opo_studio",
    dependeDe: ["core.clavis"],
    status: "beta",
    trialDias: 14,
  },

  ...RETAIL_EXTENSION_CATALOG,
]
